/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColonySlugIndexRouteImport } from './routes/$colonySlug/index'
import { Route as ColonySlugPublicRouteImport } from './routes/$colonySlug/public'
import { Route as ColonySlugManagerRouteImport } from './routes/$colonySlug/manager'
import { Route as ColonySlugLoginRouteImport } from './routes/$colonySlug/login'
import { Route as ColonySlugGuardRouteImport } from './routes/$colonySlug/guard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonySlugIndexRoute = ColonySlugIndexRouteImport.update({
  id: '/$colonySlug/',
  path: '/$colonySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonySlugPublicRoute = ColonySlugPublicRouteImport.update({
  id: '/$colonySlug/public',
  path: '/$colonySlug/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonySlugManagerRoute = ColonySlugManagerRouteImport.update({
  id: '/$colonySlug/manager',
  path: '/$colonySlug/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonySlugLoginRoute = ColonySlugLoginRouteImport.update({
  id: '/$colonySlug/login',
  path: '/$colonySlug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonySlugGuardRoute = ColonySlugGuardRouteImport.update({
  id: '/$colonySlug/guard',
  path: '/$colonySlug/guard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$colonySlug/guard': typeof ColonySlugGuardRoute
  '/$colonySlug/login': typeof ColonySlugLoginRoute
  '/$colonySlug/manager': typeof ColonySlugManagerRoute
  '/$colonySlug/public': typeof ColonySlugPublicRoute
  '/$colonySlug/': typeof ColonySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$colonySlug/guard': typeof ColonySlugGuardRoute
  '/$colonySlug/login': typeof ColonySlugLoginRoute
  '/$colonySlug/manager': typeof ColonySlugManagerRoute
  '/$colonySlug/public': typeof ColonySlugPublicRoute
  '/$colonySlug': typeof ColonySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$colonySlug/guard': typeof ColonySlugGuardRoute
  '/$colonySlug/login': typeof ColonySlugLoginRoute
  '/$colonySlug/manager': typeof ColonySlugManagerRoute
  '/$colonySlug/public': typeof ColonySlugPublicRoute
  '/$colonySlug/': typeof ColonySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/$colonySlug/guard'
    | '/$colonySlug/login'
    | '/$colonySlug/manager'
    | '/$colonySlug/public'
    | '/$colonySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/$colonySlug/guard'
    | '/$colonySlug/login'
    | '/$colonySlug/manager'
    | '/$colonySlug/public'
    | '/$colonySlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/$colonySlug/guard'
    | '/$colonySlug/login'
    | '/$colonySlug/manager'
    | '/$colonySlug/public'
    | '/$colonySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ColonySlugGuardRoute: typeof ColonySlugGuardRoute
  ColonySlugLoginRoute: typeof ColonySlugLoginRoute
  ColonySlugManagerRoute: typeof ColonySlugManagerRoute
  ColonySlugPublicRoute: typeof ColonySlugPublicRoute
  ColonySlugIndexRoute: typeof ColonySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$colonySlug/': {
      id: '/$colonySlug/'
      path: '/$colonySlug'
      fullPath: '/$colonySlug/'
      preLoaderRoute: typeof ColonySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$colonySlug/public': {
      id: '/$colonySlug/public'
      path: '/$colonySlug/public'
      fullPath: '/$colonySlug/public'
      preLoaderRoute: typeof ColonySlugPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$colonySlug/manager': {
      id: '/$colonySlug/manager'
      path: '/$colonySlug/manager'
      fullPath: '/$colonySlug/manager'
      preLoaderRoute: typeof ColonySlugManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$colonySlug/login': {
      id: '/$colonySlug/login'
      path: '/$colonySlug/login'
      fullPath: '/$colonySlug/login'
      preLoaderRoute: typeof ColonySlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$colonySlug/guard': {
      id: '/$colonySlug/guard'
      path: '/$colonySlug/guard'
      fullPath: '/$colonySlug/guard'
      preLoaderRoute: typeof ColonySlugGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ColonySlugGuardRoute: ColonySlugGuardRoute,
  ColonySlugLoginRoute: ColonySlugLoginRoute,
  ColonySlugManagerRoute: ColonySlugManagerRoute,
  ColonySlugPublicRoute: ColonySlugPublicRoute,
  ColonySlugIndexRoute: ColonySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
